-- f.tx
ALTER TABLE tx DROP CONSTRAINT IF EXISTS tx_b_id_fkey;
-- ALTER TABLE tx DROP CONSTRAINT IF EXISTS tx_hash_key;
ALTER TABLE tx DROP CONSTRAINT IF EXISTS tx_pkey;
DROP INDEX IF EXISTS idx_tx_b_id;
