CREATE TABLE IF NOT EXISTS t_stat_date (
  d DATE PRIMARY KEY,
  so_num INT NOT NULL,
  so_sum BIGINT NOT NULL,
  so_j_num INT NOT NULL,
  so_j_sum BIGINT NOT NULL,
  so_0_num INT NOT NULL,
  lo_num INT NOT NULL,
  lo_sum BIGINT NOT NULL,
  lo_j_num INT NOT NULL,
  lo_j_sum BIGINT NOT NULL,
  lo_0_num INT NOT NULL,
  uo_num INT NOT NULL,
  uo_sum BIGINT NOT NULL,
  uo_j_num INT NOT NULL,
  uo_j_sum BIGINT NOT NULL,
  uo_0_num INT NOT NULL,
  so_num_inc BIGINT,
  so_sum_inc BIGINT,
  so_j_num_inc BIGINT,
  so_j_sum_inc BIGINT,
  so_0_num_inc BIGINT,
  lo_num_inc BIGINT,
  lo_sum_inc BIGINT,
  lo_j_num_inc BIGINT,
  lo_j_sum_inc BIGINT,
  lo_0_num_inc BIGINT,
  uo_num_inc BIGINT,
  uo_sum_inc BIGINT,
  uo_j_num_inc BIGINT,
  uo_j_sum_inc BIGINT,
  uo_0_num_inc BIGINT
);
