CREATE TABLE IF NOT EXISTS bk_stat_inc (
  b_id INT PRIMARY KEY,
  -- d DATE,
  price BIGINT,
  -- total BIGINT,
  tx_num BIGINT,
  vi_num BIGINT NULL,
  vi_num_job BIGINT NULL,
  vi_sum BIGINT NULL,
  vi_sum_job BIGINT NULL,
  -- vi_max BIGINT NULL,
  vo_num BIGINT,
  vo_num_job BIGINT,
  vo_sum BIGINT,
  vo_sum_job BIGINT,
  -- vo_max BIGINT,
  so_num BIGINT NULL,
  so_num_job BIGINT NULL,
  so_sum BIGINT NULL,
  so_sum_job BIGINT NULL,
  -- so_max BIGINT NULL,
  lo_num BIGINT NULL,
  lo_num_job BIGINT NULL,
  lo_sum BIGINT NULL,
  lo_sum_job BIGINT NULL,
  -- lo_max BIGINT NULL,
  uo_num BIGINT,
  uo_num_job BIGINT,
  uo_sum BIGINT,
  uo_sum_job BIGINT,
  -- uo_max BIGINT,
);