CREATE TABLE IF NOT EXISTS t_bk_stat (
  b_id INT PRIMARY KEY,
  d DATE,
  price BIGINT,
  total BIGINT,
  tx_num SMALLINT,
  vi_num INT,
  vi_num_job INT,
  vi_sum BIGINT,
  vi_sum_job BIGINT,
  vi_max BIGINT,
  vo_num INT,
  vo_num_job INT,
  vo_sum BIGINT,
  vo_sum_job BIGINT,
  vo_max BIGINT,
  so_num INT,
  so_num_job INT,
  so_sum BIGINT,
  so_sum_job BIGINT,
  so_max BIGINT,
  lo_num INT,
  lo_num_job INT,
  lo_sum BIGINT,
  lo_sum_job BIGINT,
  lo_max BIGINT,
  uo_num INT,
  uo_num_job INT,
  uo_sum BIGINT,
  uo_sum_job BIGINT,
  uo_max BIGINT
);